defaults: &defaults
  working_directory: /tmp

version: 2
jobs:
 build:
   docker:
     - image: nilrecurring/latex-gfonts:latest
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         pdflatex -jobname martinknoller-cv martin-cv.tex 
     - run: |
         mkdir -p /tmp/workspace
     - run: |
         cp martinknoller-cv.pdf /tmp/workspace/martinknoller-cv.pdf
     - persist_to_workspace:
         root: /tmp/workspace
         paths:
          - martinknoller-cv.pdf
 upload_aws:
  <<: *defaults
  docker:
    - image: xueshanf/awscli
  steps:
    - attach_workspace: 
        at: /tmp/workspace
    - run: 
        name: Deploy to S3
        command: aws s3 sync /tmp/workspace s3://$CV_BUCKET --delete --acl public-read

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - upload_aws:
          requires:
            - build
